# Generated by Django 3.2.3 on 2021-06-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_attendancedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='class_left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancedetail',
            unique_together={('attendance_field', 'date')},
        ),
    ]
