# Generated by Django 3.2.3 on 2021-06-16 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('role', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.course'),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('author', 'timestamp')},
        ),
    ]
