# Generated by Django 3.2.3 on 2021-06-29 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0005_auto_20210616_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studymaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='study_material/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.course')),
            ],
        ),
    ]
