# Generated by Django 3.2.3 on 2021-06-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0006_studymaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='video',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
