# Generated by Django 3.2.3 on 2021-07-09 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0007_studymaterial_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('details', models.TextField()),
                ('isapproved', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.student')),
            ],
        ),
    ]
