# Generated by Django 3.2.3 on 2021-07-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0008_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='fro',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='to',
            field=models.DateField(null=True),
        ),
    ]
