# Generated by Django 3.2.3 on 2021-09-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0012_alter_sgpa_sgpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
