# Generated by Django 3.2.3 on 2021-09-13 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0013_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.batch'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='batch',
            field=models.ManyToManyField(blank=True, null=True, to='role.Batch'),
        ),
    ]
