# Generated by Django 3.2.3 on 2021-09-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0015_auto_20210913_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='student',
        ),
        migrations.AddField(
            model_name='batch',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, to='role.Student'),
        ),
        migrations.RemoveField(
            model_name='batch',
            name='teacher',
        ),
        migrations.AddField(
            model_name='batch',
            name='teacher',
            field=models.ManyToManyField(blank=True, null=True, to='role.Teacher'),
        ),
    ]
