# Generated by Django 3.2.3 on 2021-09-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0016_auto_20210913_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='isapproved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
